version: '3.7'

volumes:
    secretaria-fiap-mysql:

networks:
    secretaria-fiap-net:
        driver: 'bridge'

services:
    db:
        container_name: secretaria-fiap-db
        image: mysql:8.0
        volumes:
            - secretaria-fiap-mysql:/var/lib/mysql
        restart: always
        tty: true
        ports:
            - "3308:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=${DB_PASS}
          - MYSQL_PASSWORD=${DB_PASS}
          - MYSQL_DATABASE=${DB_NAME}  
        networks:
            - secretaria-fiap-net

    webserver:
        container_name: secretaria-fiap-nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/app
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "5000:80"
        restart: always
        depends_on:
            - db
            - app
        tty: true
        networks:
            - secretaria-fiap-net

    app:
        container_name: secretaria-fiap-php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/app
        ports:
            - "9000"
        restart: always
        tty: true
        networks:
            - secretaria-fiap-net